"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { CheckCircle2, Download, Sparkles } from "lucide-react";

export default function RepeatPaymentThankYouPage() {
  const searchParams = useSearchParams();
  const customerName = searchParams.get("name")?.trim() || "Repeat user";
  const customerPhone = searchParams.get("phone")?.trim() || "Not provided";
  const customerEmail = searchParams.get("email")?.trim() || "Not provided";
  const transactionId = searchParams.get("transactionId")?.trim() || "Not provided";
  const paidAt = new Date();
  const invoiceId = `RPT-${paidAt.getFullYear()}${String(paidAt.getMonth() + 1).padStart(2, "0")}${String(paidAt.getDate()).padStart(2, "0")}-${String(paidAt.getHours()).padStart(2, "0")}${String(paidAt.getMinutes()).padStart(2, "0")}${String(paidAt.getSeconds()).padStart(2, "0")}`;
  const invoiceDate = paidAt.toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });

  function downloadInvoice() {
    void (async () => {
      const { jsPDF } = await import("jspdf");
      const pdf = new jsPDF({ unit: "pt", format: "a4" });
      pdf.setFillColor(18, 24, 32);
      pdf.rect(0, 0, 595, 120, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(24);
      pdf.text("REPEAT INVOICE", 44, 68);
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(11);
      pdf.text("Thanks a lot for using Repeat", 44, 92);

      pdf.setTextColor(30, 30, 30);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(13);
      pdf.text("Payment Details", 44, 160);

      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(11);
      const lines = [
        `Invoice ID: ${invoiceId}`,
        `Date: ${invoiceDate}`,
        "Product: Repeat Premium Access",
        "Amount: Rs 39",
        "Status: Paid",
        `Customer Name: ${customerName}`,
        `Phone Number: ${customerPhone}`,
        `Email: ${customerEmail}`,
        `Transaction ID: ${transactionId}`,
      ];
      let y = 188;
      for (const line of lines) {
        pdf.text(line, 44, y);
        y += 22;
      }
      pdf.setFontSize(10);
      pdf.setTextColor(110, 110, 110);
      pdf.text("Generated by Repeat", 44, 760);
      pdf.save(`${invoiceId}.pdf`);
    })();
  }

  return (
    <div className="min-h-dvh bg-[radial-gradient(ellipse_at_top,rgba(16,185,129,0.18),transparent_42%),#030303] px-4 py-8 sm:px-6 sm:py-10">
      <div className="mx-auto w-full max-w-2xl rounded-[2rem] border border-emerald-300/25 bg-gradient-to-b from-emerald-500/14 via-emerald-500/8 to-transparent p-6 shadow-[0_28px_80px_rgba(0,0,0,0.45)] backdrop-blur-xl sm:p-8">
        <div className="inline-flex items-center gap-2 rounded-full border border-emerald-300/35 bg-emerald-300/15 px-3 py-1 text-xs text-emerald-100">
          <Sparkles className="size-3.5" />
          Payment successful
        </div>
        <div className="mt-4 flex items-center gap-3">
          <CheckCircle2 className="size-8 text-emerald-300" />
          <h1 className="text-3xl font-semibold tracking-tight text-white">
            Thanks a lot for using Repeat
          </h1>
        </div>
        <p className="mt-3 text-sm text-emerald-50/85">
          Your payment is confirmed and your Repeat premium access is now active.
        </p>

        <div className="mt-5 rounded-2xl border border-white/10 bg-black/25 p-4">
          <p className="text-xs uppercase tracking-[0.18em] text-zinc-400">Invoice details</p>
          <p className="mt-2 text-sm text-zinc-100">Invoice ID: {invoiceId}</p>
          <p className="mt-1 text-sm text-zinc-300">Date: {invoiceDate}</p>
          <p className="mt-1 text-sm text-zinc-300">Amount: Rs 39</p>
          <p className="mt-1 text-sm text-zinc-300">Name: {customerName}</p>
          <p className="mt-1 text-sm text-zinc-300">Phone: {customerPhone}</p>
          <p className="mt-1 text-sm text-zinc-300">Email: {customerEmail}</p>
          <p className="mt-1 text-sm text-zinc-300">Transaction ID: {transactionId}</p>
        </div>

        <div className="mt-6 flex flex-wrap gap-3">
          <button
            type="button"
            onClick={downloadInvoice}
            className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-medium text-zinc-900 transition-opacity hover:opacity-90 active:scale-[0.98]"
          >
            <Download className="size-4" />
            Download invoice
          </button>
          <Link
            href="/repeat"
            className="inline-flex rounded-full border border-white/20 px-4 py-2 text-sm text-zinc-100 transition-colors hover:bg-white/10 active:scale-[0.98]"
          >
            Go to Repeat now
          </Link>
        </div>
      </div>
    </div>
  );
}
